### ISSUE TITLE
Compilation error on Elixir 1.12

### ISSUE THREAD

**Issue by TylerPachal** [tsutsu/signal_handler#3]
Hello, I have upgraded a project to Elixir 1.12.3 and this dependency no longer compiles:

```
$ cat .tool-versions 
erlang 23.1.1
elixir 1.12.3-otp-23

$ mix compile --force
Compiling 3 files (.ex)
warning: redefining module System.SignalHandler (current version loaded from /Users/tyler/.asdf/installs/elixir/1.12.3-otp-23/bin/../lib/elixir/ebin/Elixir.System.SignalHandler.beam)
  lib/signal_handler.ex:1


== Compilation error in file lib/signal_handler/graceful_shutdown.ex ==
** (CompileError) lib/signal_handler/graceful_shutdown.ex:4: undefined function handle/2
```

I received the same error on `1.12.0`.  It was previously working with `1.11.1`.

---

I took a look through the [release notes](https://elixir-lang.org/blog/2021/05/19/elixir-v1-12-0-released/) and didn't see anything that should break this.  Although I do see that there is now a built-in `System.trap_signal/3` so for now I will try to use that instead.
